Repository ke444a/cw2_api_mashup, pull requests merged in 2022-12, with the labels that each got.

#8 Draft of Home page
  css/home.css
  css/slick.css
  img/introduction-img.png
  index.html
  js/main.js
  js/slick.min.js
Labels: page

#25 a slightly better looking desc page
  descriptionPage.html
  js/description.js
Labels: enhancement

#26 Home Page
  css/home.css
  img/action.png
  img/adventure.png
  img/horror.png
  img/indie.png
  img/introduction-img.png
  img/rpg.png
  img/simulation.png
  img/sports.png
  img/strategy.png
  index.html
  js/main.js
Labels: page

#30 Consistency edits
  contactUs.html
  descriptionPage.html
  help.html
  index.html
  termsOfUse.html
Labels: page

#31 Browse page
  browse.html
  css/browse-page.css
  js/browse.js
Labels: page

#38 Enhanced design of the Descriptions page
  css/description.css
  descriptionPage.html
  img/metacritic.png
  js/description.js
Labels: enhancement

#44 Improved design of Browse page after API implementation
  browse.html
  css/browse-page.css
  js/browse.js
Labels: enhancement

#45 Improved styling of Category page after API result
  category.html
  js/category.js
Labels: enhancement

#46 Changed the parameters of button appearance
  css/browse-page.css
Labels: enhancement

#51 Updated README file
  README.md
  js/browse.js
  js/category.js
Labels: documentation
